@startuml
!pragma layout smetana
'https://plantuml.com/sequence-diagram

class User {
-String userID
-String password
List<String> allergies
String cuisineRestriction
Duration timeRestriction
Float costRestriction
RecipeHistory history
}

class RecipeHistory{

}

class Inventory {
list ingredients

}

class callRecipe {
}

class QueryAPI {
}

class QueryDatabase {
}

@enduml