@startuml
!pragma layout smetana
'https://plantuml.com/sequence-diagram

class User {
-String userID
-String password
List<String> allergies
List<String> cuisineRestriction
Duration timeRestriction
Float costRestriction
RecipeHistory history

void addItem(List[String] items)
void removeItem(List[String] items)
}

class RecipeHistory{
List<Recipe> recipesDone
-void addRecipe(Recipe recipe)
}

class Recipe{
List<String> ingredients
String instructions
float flavourScore
float handyScore
int timesDone
void doneNow(float flavourScore, float handyScore)
}

class Inventory {
List<String> veges
List<String> meat
List<String> seasonings
List<String> other
}

class callRecipe {
}

class QueryAPI {
}

class QueryDatabase {
}

RecipeHistory -- Recipe
User *-- Inventory
User *-- RecipeHistory

@enduml